{% set name = "filprofiler" %}
{% set version = "2021.04.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pythonspeed/filprofiler/archive/refs/heads/152-aligned-alloc.zip
  sha256: 257229a046a6bbbba2ca456d113ba752344fb9e92cf1e99140b6c5ea91ca9be1

build:
  number: 0
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - rust
  run:
    - python
    - threadpoolctl

test:
  requires:
    - python
    - pytest
    - pip
    - c-compiler
    - cxx-compiler
    - fortran-compiler
  source_files:
    - tests/
    - tests/*
    - requirements-dev.txt
    - Makefile
  commands:
    - pip install -r requirements-dev.txt
    - make test-python-no-deps

about:
  home: https://github.com/pythonspeed/filprofiler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A memory profiler for Python, aimed at scientists and data scientists.

  description: |
    A memory profiler for Python, aimed at scientists and data scientists.
    Fil will track memory allocations from Python, C, C++, and more, and will
    tell you what code was responsible for peak memory usage with an easy-to-use
    visualization.
  doc_url: https://github.com/pythonspeed/filprofiler
  dev_url: https://github.com/pythonspeed/filprofiler

extra:
  recipe-maintainers:
    - itamarst
