{% set name = "filprofiler" %}
{% set version = "2023.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pythonspeed/filprofiler/archive/{{ version }}.zip
  sha256: a3465fc73f447df45fe9158509b701f2e992e788356b91bee88d48928f6ef924

build:
  number: 1
  skip: true  # [win or python_impl == "pypy"]
  entry_points:
    - fil-profile = filprofiler._script:stage_1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - lld
    - {{ compiler('rust') }}
    - make
    - setuptools-rust
    - setuptools_scm
    - wheel
  host:
    - python
    - pip
    - setuptools-rust
    - setuptools_scm
    - wheel
  run:
    - python
    - threadpoolctl

test:
  requires:
    - pytest
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - lld
    - numexpr
    - make
    - psutil
    - pampy
  source_files:
    - tests/
    - tests/*
    - Makefile
  commands:
    - fil-profile --help
    - mkdir /tmp/fil
    - cp -r Makefile tests /tmp/fil
    # Don't run all tests, for some reason have issues when we do
    # (https://github.com/pythonspeed/filprofiler/issues/210).
    - cd /tmp/fil && pytest tests/test_endtoend.py -k test_threaded_allocation_tracking

about:
  home: https://github.com/pythonspeed/filprofiler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A memory profiler for Python, aimed at scientists and data scientists.

  description: |
    A memory profiler for Python, aimed at scientists and data scientists.
    Fil will track memory allocations from Python, C, C++, and more, and will
    tell you what code was responsible for peak memory usage with an easy-to-use
    visualization.
  doc_url: https://github.com/pythonspeed/filprofiler
  dev_url: https://github.com/pythonspeed/filprofiler

extra:
  recipe-maintainers:
    - itamarst
