{% set name = "filprofiler" %}
{% set version = "2021.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pythonspeed/filprofiler/archive/{{ version }}.tar.gz
  sha256: fd6424399bc5b21670c9eed0fb94b709fd07fc3332d0febdb88f9f88245433f1

build:
  number: 0
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - lld
  host:
    - python
    - pip
    - rust
    - setuptools-rust
  run:
    - python
    - threadpoolctl

test:
  requires:
    - python
    - pytest
    - pip
    - c-compiler
    - cxx-compiler
    - fortran-compiler
    - lld
  source_files:
    - tests/
    - tests/*
    - requirements-dev.txt
    - Makefile
  commands:
    - pip install -r requirements-dev.txt
    - mkdir /tmp/fil
    - cp -r Makefile tests /tmp/fil
    # Don't run all tests, for some reason have issues when we do
    # (https://github.com/pythonspeed/filprofiler/issues/210).
    - cd /tmp/fil && pytest tests/test_endtoend.py -k test_threaded_allocation_tracking

about:
  home: https://github.com/pythonspeed/filprofiler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A memory profiler for Python, aimed at scientists and data scientists.

  description: |
    A memory profiler for Python, aimed at scientists and data scientists.
    Fil will track memory allocations from Python, C, C++, and more, and will
    tell you what code was responsible for peak memory usage with an easy-to-use
    visualization.
  doc_url: https://github.com/pythonspeed/filprofiler
  dev_url: https://github.com/pythonspeed/filprofiler

extra:
  recipe-maintainers:
    - itamarst
